odhcpd: fix compilation with musl 1.2.4
Use the plain function instead of the gone syscall.

Fixes error in the form of:
build_dir/target-mips_34kc_musl/odhcpd-2015-11-19/src/odhcpd.c: In function 'odhcpd_time':
build_dir/target-mips_34kc_musl/odhcpd-2015-11-19/src/odhcpd.c:476:10: error: 'SYS_clock_gettime' undeclared (first use in this function); did you mean 'SYS_clock_gettime64'?
  syscall(SYS_clock_gettime, CLOCK_MONOTONIC, &ts);
          ^~~~~~~~~~~~~~~~~
          SYS_clock_gettime64

Change-Id: If3e878911dad7ff2d3899da18339b26a7effb5e8
Signed-off-by: Ronghua Zeng <quic_ronghuaz@quicinc.com>