odhcp6c: fix comcompilation with musl 1.2.4
Use the plain function instead of the gone syscall.

Fixes error in the form of:
build_dir/target-mips_34kc_musl/odhcp6c-2015-07-29/src/odhcp6c.c:461:10: error: 'SYS_clock_gettime' undeclared (first use in this function); did you mean 'SYS_clock_gettime32'?
  syscall(SYS_clock_gettime, CLOCK_MONOTONIC, &t);
          ^~~~~~~~~~~~~~~~~
          SYS_clock_gettime32

Change-Id: Id3a113abbcaa45776b15fc9050ff165eeb8df377
Signed-off-by: Ronghua Zeng <quic_ronghuaz@quicinc.com>