tools/scons: Fix build error with python3
This change adds support to use scons with python3,
to fix below build error:
AttributeError: module 'collections' has no attribute 'Callable':

Change-Id: I1959038af4dd5261477d5ecad6dd27779f061184
Signed-off-by: Sathishkumar Kumar <quic_satku@quicinc.com>
(cherry picked from commit 13a665163cf562c09b68fdb285e42533c367d4a7)