Revert "dnsmasq: follow upstream dnsmasq pre-v2.81"
This reverts commit a6a8fe0be5cd2edb1560bfc3f3094c3d34f2d2b0.

buildbot found an error
option.c: In function 'dhcp_context_free':
option.c:1042:15: error: 'struct dhcp_context' has no member named 'template_interface'
       free(ctx->template_interface);

revert for the moment

Signed-off-by: Kevin Darbyshire-Bryant <ldir@darbyshire-bryant.me.uk>
(cherry picked from commit 18e02fa20c949e17ff77d821e464a44640ca4c52)

Change-Id: Ia383c2faeba9cfe395ad16d9ebba9fec83ee74dc
Signed-off-by: Madhurya Kandamuru <quic_madhurya@quicinc.com>